fix merge error:
argparse.ArgumentError: argument -R/--repo-paths: conflicting option strings: -R, --repo-paths

caused by duplicate call to parser.add_argument()

Change-Id: I2d096ffeb438568cc2ee9a2a33e8d70ff49f05b6